architect:
- eivinhb
decrypt:
  settings.xml: "repo/.scrt/settings.xml.asc"
  pubring.gpg:  "repo/.scrt/pubring.pgp.asc"
  secring.gpg:  "repo/.scrt/secring.pgp.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pjcabi-gpg,sonatype --settings /home/r/settings.xml
  commanders:
  - eivinhb
