architect:
- eivinhb
decrypt:
  settings.xml: "repo/.scrt/settings.xml.asc"
  pubring.gpg:  "repo/.scrt/pubring.pgp.asc"
  secring.gpg:  "repo/.scrt/secring.pgp.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -P 'jcabi-gpg,sonatype,!xdoc' -Dmaven.javadoc.skip=true --settings /home/r/settings.xml -B
  commanders:
  - eivinhb
